---
- name: Set up website with custom page
  hosts: all
  become: yes
  vars:
    index_content: "<h1>Welcome to {{ package }} server</h1>"
    package: nginx
    http_port: 8080

  tasks:
    - name: Install {{ package }}
      apt:
        name: "{{ package }}"
        state: present
       
    - name: start {{ package }} service
      service:
        name: "{{ package }}"
        state: started
        enabled: yes
        
    
    - name: create custom index.html
      copy:
        dest: /var/www/html/index.html
        content: "{{ index_content }}"
      notify: Restart {{ package }}
    
    - name: deploy {{ package }} configuration
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/{{ package }}/{{ package }}.conf
      notify: restart {{ package }}

  handlers:
    - name: Restart {{ package }}
      service:
        name: "{{ package }}"
        state: restarted